spring.datasource.url=jdbc:postgresql://dpg-d6hhhzeh46gs73def4ng-a:5432/worker_database
spring.datasource.username=worker_database_user
spring.datasource.password=SZCkWmrjAsepPK91q2tpfLMKJdNklagf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true