
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6nhhrrh46gs73def4ng-a.oregon-postgres.render.com:5432/worker_database
spring.datasource.username=worker_database_user
spring.datasource.password=SZCkWmrjAsepPK91q2tpfLMKJdNklagf

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true